### ISSUE TITLE
Vertical scrolling on the main menu shouldn't be allowed

### ISSUE THREAD

**Issue by rolemadelen** [rolemadelen/minimalist-blog#11]
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/101682300/232571218-526cfb7f-d3cb-420f-a6de-bddda6a4ed93.gif)

**Comment by Sky-De** [comment]
Assign this to me
I will take a look as soon as it's possible

**Comment by rolemadelen** [comment]
@Sky-De 

Oh I just saw this, my bad. 
I normally use issues (especially when it's just my personal project) as a reminder for myself, but thanks for the comment anyway.

As I updated my blog, this is no longer an issue. So I'll close it.
